badge-server-url: http://badges.falsifiable.us
metadata:
  access_right: open
  license: CC-BY-4.0
  publication_type: article
  upload_type: publication
pipelines:
  mypipe:
    envs:
      host:
        args: []
    parameters: []
    path: pipelines/mypipe
    requirements: {}
    stages:
    - download-data
    - run-anaylsis
    - plot-graphs
search_sources:
- popperized
version: 1
